spring.datasource.url=jdbc:h2:mem:pcbuilder;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=false
spring.jackson.property-naming-strategy=SNAKE_CASE
pcbuilder.parts.path=../parts
rawg.api.key=YOUR_RAWG_API_KEY_HERE
rawg.api.url=https://api.rawg.io/api
userbenchmark.search.url=https://www.userbenchmark.com/Search?search=
